---
- hosts: localhost
  connection: local
  vars_files:
     - vars/homebrew.yaml

  roles:
    - role: geerlingguy.homebrew
    - role: jamescarr.dotfiles
      zsh_theme: bureau
      oh_my_zsh_plugins:
        - git
        - osx

  tasks:
    - name: Say All Done!
      osx_say:
        msg: "ALL DONE!"
