---
- hosts: localhost
  connection: local
  vars_files:
     - vars/homebrew.yaml

  roles:
    - geerlingguy.homebrew
    - jamescarr.dotfiles

  tasks:
    - name: Say All Done!
      osx_say:
        msg: "ALL DONE!"
