---
- hosts: localhost
  connection: local
  vars:
    homebrew_taps:
      - caskroom/cask
    homebrew_installed_packages:
      - tmux
      - macvim
    homebrew_cask_apps:
      - spotify
      - iterm2
  roles:
    - geerlingguy.homebrew
  tasks:
    - name: Say hello world
      osx_say:
        msg: "Hello World!"
